//CREATE NEW USER
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_RESPONSE_SUCCESS = 'CREATE_USER_RESPONSE_SUCCESS';
export const CREATE_USER_RESPONSE_FAILURE = 'CREATE_USER_RESPONSE_FAILURE'